title: Mahmoud's Portfolio
description: Mahmoud's Portfolio

permalink: pretty

url: https://mahmoudnouh.xyz

plugins:
  - jekyll-sitemap

exclude:
  - tmp
  - webp.bat

collections:
  Projects:
    output: true
